org: taylorjg
app: dvla-viewer
service: dvla-viewer

build:
  esbuild:
    bundle: true
    minify: true

provider:
  name: aws
  runtime: nodejs24.x
  environment:
    API_KEY: ${param:apiKey}
  httpApi:
    cors: true

functions:
  search:
    handler: lookup.handler
    events:
      - httpApi:
          method: get
          path: /api/lookup
